apps/funcionarios/urls.py
from django.urls import path  # , include
from .views import WorkerList, WorkerEdit, WorkerDelete, WorkerCreate

urlpatterns = [
    path('', WorkerList.as_view(), name='list_worker'),
    path('edit/<int:pk>', WorkerEdit.as_view(), name='update_worker'),
    path('delete/<int:pk>', WorkerDelete.as_view(), name='delete_worker'),
    path('new/', WorkerCreate.as_view(), name='create_worker'),


]

company/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('workers/', include('apps.funcionarios.urls')),
    path('company/', include('apps.empresas.urls')),
    path('departaments/', include('apps.departamentos.urls')),
    path('documents/', include('apps.documentos.urls')),
    path('overtime/', include('apps.registro_hora_extra.urls')),
    path('', include('apps.core.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from apps.funcionarios.models import Funcionario
from django.urls import reverse

# Create your models here.


class Documento(models.Model):
    description = models.CharField(max_length=100, verbose_name='descrição')
    belongs_to = models.ForeignKey(Funcionario, verbose_name='pertence a',
                                   on_delete=models.PROTECT)
    file = models.FileField(upload_to='Documentos', verbose_name='arquivo')

    def get_absolute_url(self):
        return reverse("update_worker", args=[self.belongs_to.id])

    def __str__(self):
        return self.description

apps/funcionarios/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa
from django.db.models import Sum
# Create your models here.


class Funcionario(models.Model):
    name = models.CharField(max_length=100, verbose_name='nome')
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departaments = models.ManyToManyField(
        Departamento, verbose_name='departamentos')
    company = models.ForeignKey(
        Empresa, on_delete=models.PROTECT, verbose_name='Empresa',
        null=True, blank=True)

    @property
    def total_overtime(self):
        return self.registrohoraextra_set.filter(used=False).aggregate(
            Sum('hours'))['hours__sum']

    def get_absolute_url(self):
        return reverse("list_worker")

    def __str__(self):
        return self.name 

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse
from apps.funcionarios.models import Funcionario


class RegistroHoraExtra(models.Model):
    reason = models.CharField(max_length=50, verbose_name='Motivo')
    worker = models.ForeignKey(
        Funcionario, on_delete=models.PROTECT, verbose_name='Funcionario')
    hours = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Horas')
    used = models.BooleanField(default=False, verbose_name='Usadas')
    def get_absolute_url(self):
        return reverse("list_overtime")
    

    def __str__(self):
        return self.reason

apps/funcionarios/views.py
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from .models import Funcionario
from django.urls import reverse_lazy
from django.contrib.auth.models import User


class WorkerList(ListView):
    model = Funcionario

    # sobrescreve a função get_queryset para apresentar somente funcionarios
    # da empresa logada
    def get_queryset(self):
        log_company = self.request.user.funcionario.company
        return Funcionario.objects.filter(company=log_company)


class WorkerEdit(UpdateView):
    model = Funcionario
    fields = ['name', 'departaments']


class WorkerDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_worker')


class WorkerCreate(CreateView):
    model = Funcionario
    fields = ['name', 'departaments']

    def form_valid(self, form):
        worker = form.save(commit=False)
        username = worker.name.split(' ')[0] + worker.name.split(' ')[1]
        worker.company = self.request.user.funcionario.company
        worker.user = User.objects.create(username=username)
        worker.save()

        return super(WorkerCreate, self).form_valid(form)

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}

Delete <br>

<form method="post">
  {% csrf_token %}
  <div class="form-group">
    <h3>Tem certeza que deseja deletar{{ object }}</h3>
    {{form}}
  </div>
  <div class="form-check">
    <button class="btn btn-outline-danger" type="submit"><i class="bi bi-trash3"></i> Deletar</button>
    <a class="btn btn-outline-primary" href="{% url 'list_worker' %}"><i class="bi bi-x-circle"></i> Cancelar</a>
  </div>

</form>

{% endblock %} 

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap%}

{% block main %}
<h1 class="text-dark"> Editar</h1>
<form method="post">
  {% csrf_token %}
  {{form|bootstrap}}
  <br><br>
  <button class="btn btn-primary" type="submit">
    Salvar alterações
  </button>
</form>
<br>
<a href="{% url 'new_document' object.id %}" class="btn btn-outline-success"> Adicionar novo documento </a>
<br>
<h3>Documentos</h3>
<br>
 {% for document in object.documento_set.all %}
  <a href="{{ document.file.url }}">{{document}}</a>
  <br>
 {% endfor  %}
<br>
<h3>Registro de horas extras</h3>
<ul>
  {% for overtime in object.registrohoraextra_set.all %}
    <a href="{% url 'edit_overtime' overtime.id %}"><li>{{overtime.reason}} -|- {{overtime.hours}} horas</li></a>
  {% endfor %}
</ul>
<h3>Registro de horas extras ||{{ object.total_overtime }}</h3>


<br>
{% endblock %} 

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}

  <div class="row">
    <div class="col-10">
      <h3> List </h3> <br>
    </div>
    <div class="col-2">
      <a class="btn btn-outline-success" href="{% url 'home' %}"><i class="bi bi-house-fill"></i>Home</a>
    </div>
  </div>
  <br>
  <div class="row">
  {% for worker in object_list %}
      <div class="col-10">
        <a href="{% url 'update_worker' worker.id%}" class="a_worker">
          {{ worker }}
        </a>
      </div>
      <div class="col-2">
        <a title="Deletar" class="btn btn-outline-danger" href="{% url 'delete_worker' worker.id %}"><i class="bi bi-trash3"></i></a>
      </div>
      <br>
      <br> 
      {% endfor %}
  </div>
  <div class="row">
   <div class="col-10"></div>
    <div class="col-2">
      <div class="align-bottom">
        <a title="Criar" class="btn btn-info" href="{% url 'create_worker' %}" style="border-radius: 50%;"><i class="bi bi-person-plus-fill"></i></a>
      </div>
    </div>
  </div>
  
{% endblock %}